import { 
    Activity, 
    History, 
    BookOpen, 
    Brain, 
    Folder, 
    GraduationCap, 
    PlusCircle, 
    Sparkles, 
    Target, 
    Trophy, 
    Users } from "lucide-react"

 export const mainCards = [
      {
      title: "Add Questions",
      description: "Expand your question bank",
      icon: PlusCircle,
      color: "text-green-600",
      bgColor: "bg-green-50 dark:bg-green-950/20",
      path: "/protected/community/add-question",
    },
    {
      title: "Study Topics",
      description: "Browse and study by topic",
      icon: BookOpen,
      color: "text-blue-600",
      bgColor: "bg-blue-50 dark:bg-blue-950/20",
      path: "/protected/topics",
    },
    {
      title: "Community",
      description: "Learn with others",
      icon: Users,
      color: "text-green-600",
      bgColor: "bg-green-50 dark:bg-green-950/20",
      path: "/protected/community",
    },
    {
      title: "Practice Exam",
      description: "Take practice exams",
      icon: Brain,
      color: "text-purple-600",
      bgColor: "bg-purple-50 dark:bg-purple-950/20",
      path: "/protected/exam/setup",
    },
    {
      title: "Community Exams",
      description: "User-created exams",
      icon: GraduationCap,
      color: "text-orange-600",
      bgColor: "bg-orange-50 dark:bg-orange-950/20",
      path: "/protected/exams",
    },
    {
      title: "Daily Question",
      description: "Today's challenge",
      icon: Sparkles,
      color: "text-pink-600",
      bgColor: "bg-pink-50 dark:bg-pink-950/20",
      path: "/protected/question-of-day",
    },
    {
      title: "Weekly Challenge",
      description: "Compete with others",
      icon: Target,
      color: "text-red-600",
      bgColor: "bg-red-50 dark:bg-red-950/20",
      path: "/protected/challenges",
    },
    {
      title: "My Collections",
      description: "Organized questions",
      icon: Folder,
      color: "text-teal-600",
      bgColor: "bg-teal-50 dark:bg-teal-950/20",
      path: "/protected/collections",
    },
    {
      title: "Exam History",
      description: "View past results",
      icon: History,
      color: "text-indigo-600",
      bgColor: "bg-indigo-50 dark:bg-indigo-950/20",
      path: "/protected/exam-history",
    },
    {
      title: "Leaderboard",
      description: "Top contributors",
      icon: Trophy,
      color: "text-amber-600",
      bgColor: "bg-amber-50 dark:bg-amber-950/20",
      path: "/protected/leaderboard",
    },
    {
      title: "Recommendations",
      description: "Personalized for you",
      icon: Sparkles,
      color: "text-violet-600",
      bgColor: "bg-violet-50 dark:bg-violet-950/20",
      path: "/protected/recommendations",
    },
    {
      title: "Activity Feed",
      description: "Platform updates",
      icon: Activity,
      color: "text-cyan-600",
      bgColor: "bg-cyan-50 dark:bg-cyan-950/20",
      path: "/protected/activity-feed",
    },
  ]
